input {
  file {
    path => "/logs/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

filter {
  date {
    match => ["asctime", "yyyy-MM-dd HH:mm:ss,SSS"]
    target => "@timestamp"
  }

  mutate {
    remove_field => ["asctime"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "schedule-app-logs-%{+YYYY.MM.dd}"
  }
}
